### ISSUE TITLE
Error package grifts is not in GOROOT

### ISSUE THREAD

**Issue by stormenergy91** [gobuffalo/cli#142]
Hi,
cloning the cli repo and install it with `go install -v ./cmd/buffalo` I cannot run any grift (`buffalo task ...`). 
Simply:
```
$ buffalo demo_project
$ cd demo_project
$ buffalo task
```
and you get this error
```
.grifter/main.go:9:2: package grifts is not in GOROOT (/usr/local/go/src/grifts)
Usage:
  buffalo task [flags]

Aliases:
  task, t, tasks

Flags:
  -h, --help   help for task

ERRO[0000] Error: exit status 1 
```

If you try this steps with cli version v0.18.2 all works.

**Comment by sio4** [comment]
Confirmed and I am working on it.

**Comment by sio4** [comment]
Hi @paganotoni,

Would you please release a new version of `here` so the PR https://github.com/gobuffalo/here/pull/11 can take effect?
Then I will do the rest of the jobs (`go mod tidy` for `cli` package) to fix this issue.

**Comment by paganotoni** [comment]
All set @sio4

**Comment by sio4** [comment]
Hi @stormenergy91 

The fix for this was merged into the development branch but it will need more time to release a new version of CLI. During the gap, you can try to use the development version.

I will close this issue now, but please feel free to reopen it if you find any related issues even after the release.

Thank you!
